default:
  image: docker:${DOCKER_VERSION}
  interruptible: true
  timeout: 90m
  tags:
    - dind

stages:
  - "build"
  - "test"

variables:
  DOCKER_VERSION: 20.10.8
  DOCKER_BUILDKIT: 1
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_TLS_VERIFY: ""
  GIT_DEPTH: 1

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

include:
  - local: '.gitlab/pipeline-templates/build/kaniko.gitlab-ci.yml'
  - local: '.gitlab/pipeline-templates/test/unit-test.gitlab-ci.yml'
  - local: '.gitlab/pipeline-templates/test/go-lint.gitlab-ci.yml'
  
.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/