version: '3'

tasks:
  docker:dev:
    env:
      COMPOSE_TARGET: "dev"
    cmds:
      - cmd: docker compose -p acme -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up --build --force-recreate

  docker:start:
    env:
      COMPOSE_TARGET: ""
      DOCKER_BUILDKIT: 1
    cmds:
      - cmd: docker compose -p acme -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up --build --force-recreate

  docker:build:
    env:
      DOCKER_BUILDKIT: 1
      BUILD_VERSION: 0.0.0-dev
    cmds:
      - cmd: |
             docker build --build-arg BUILD_VERSION=$BUILD_VERSION \
             --build-arg BUILD_DATE="{{.BUILD_DATE}}" \
             --build-arg BUILD_VCS_REF="{{.BUILD_VCS_REF}}" \
             -t git.rykelabs.com:5050/rykelabs/acme-server:latest \
             -f docker/Dockerfile .
    vars:
      BUILD_DATE:
        sh: date
      BUILD_VCS_REF:
        sh: git rev-parse --short HEAD
    silent: false

  docker:build:clean:
    env:
      BUILD_VERSION: 0.0.0-dev
    cmds:
      - cmd: |
             docker build --no-cache \
             --build-arg BUILD_VERSION=$BUILD_VERSION \
             --build-arg BUILD_DATE="{{.BUILD_DATE}}" \
             --build-arg BUILD_VCS_REF="{{.BUILD_VCS_REF}}" \
             -t git.rykelabs.com:5050/rykelabs/acme-server:latest \
             -f docker/Dockerfile .
    vars:
      BUILD_DATE:
        sh: date
      BUILD_VCS_REF:
        sh: git rev-parse --short HEAD

  docker:deploy:
    env:
      BUILD_VERSION: 0.0.0-dev
    cmds:
      - cmd: docker buildx rm acme_builder # just in case task was exited early by the user
        ignore_error: true
      - cmd: docker buildx create --name acme_builder --use
      - cmd: docker buildx build --push --platform linux/amd64 --build-arg BUILD_VERSION=$BUILD_VERSION --build-arg BUILD_DATE="{{.BUILD_DATE}}" --build-arg BUILD_VCS_REF="{{.BUILD_VCS_REF}}" -t git.rykelabs.com:5050/rykelabs/acme-server:latest -f docker/Dockerfile .
      - cmd: docker buildx rm acme_builder
        ignore_error: true
    silent: false
    vars:
      BUILD_DATE:
        sh: date
      BUILD_VCS_REF:
        sh: git rev-parse --short HEAD

  go:build:
    env:
      CGO_ENABLED: 0
    cmds:
      - go build -ldflags="-s -w -X github.com/Celtech/ACME/cmd.Version=0.0.0-dev" -gcflags=all="-l -B" -o ./build/ssl-certify
    silent: false

  add:user:
    cmds:
      - cmd: docker exec -it rykelabs-acme-app /app/ssl-certify add {{.CLI_ARGS}}

  tester:
    cmds:
      - cmd: docker exec -it rykelabs-acme-app /app/ssl-certify test

  openapi:
    cmds:
      - cmd: swag init --md docs --codeExampleFiles docs/samples
      - cmd: rm docs/docs.go

  test:
    cmds:
      - go test -race $(go list ./... | grep -v /vendor/)
