version: '3'

tasks:
  docker:build:
    cmds:
      - cmd: docker build --no-cache -t git.rykelabs.com:5050/rykelabs/acme-server:latest -f docker/Dockerfile .
    silent: false

  docker:start:
    cmds:
      - cmd: docker compose -f docker/docker-compose.yml up --build --force-recreate 
  
  docker:deploy:
    cmds:
      - cmd: docker buildx rm acme_builder # just in case task was exited early by the user
        ignore_error: true
      - cmd: docker buildx create --name acme_builder --use
        ignore_error: true
      - cmd: docker buildx build --push --platform linux/amd64 -t git.rykelabs.com:5050/rykelabs/acme-server:latest -f docker/Dockerfile .
        ignore_error: true
      - cmd: docker buildx rm acme_builder
        ignore_error: true
    silent: false
  
  docker:deploy:test:
    cmds:
      - cmd: docker buildx rm acme_builder # just in case task was exited early by the user
        ignore_error: true
      - cmd: docker buildx create --name acme_builder --use
        ignore_error: true
      - cmd: docker buildx build --push --platform linux/amd64 -t timhinz/ssl-testing:latest -f docker/Dockerfile .
        ignore_error: true
      - cmd: docker buildx rm acme_builder
        ignore_error: true
    silent: false
  
  openapi:
    cmds:
      - task: openapiv2
      - task: openapiv3

  openapiv2:
    cmds:
      - cmd: swag init --md docs --codeExampleFiles docs/samples
      - cmd: rm docs/docs.go

  openapiv3:
    cmds:
      - cmd: docker run --rm -v $(PWD)/docs:/work $OAS3_GENERATOR_DOCKER_IMAGE generate -i /work/swagger.yaml -o /work/openapi -g openapi-yaml --minimal-update
      - cmd: docker run --rm -v $(PWD)/docs/openapi:/work $WORKER_IMAGE sh -c "rm -rf /work/.openapi-generator"
      - cmd: docker run --rm -v $(PWD)/docs/openapi:/work $WORKER_IMAGE sh -c "cp -f /work/.openapi-generator-ignore /work/openapi"
      - cmd: docker run --rm -v $(PWD)/docs:/work $OAS3_GENERATOR_DOCKER_IMAGE generate -s -i /work/swagger.json -o /work/openapi/openapi -g openapi --minimal-update
      - cmd: docker run --rm -v $(PWD)/docs/openapi:/work $WORKER_IMAGE sh -c "mv -f /work/openapi/openapi.json /work ; mv -f /work/openapi/openapi.yaml /work ; rm -rf /work/openapi"
      - cmd: rm docs/openapi/.openapi-generator-ignore
      - cmd: rm docs/openapi/README.md
    env:
      OAS3_GENERATOR_DOCKER_IMAGE: openapitools/openapi-generator-cli:latest-release
      WORKER_IMAGE: golang:1.15-alpine3.13
    silent: false