version: "3.8"

services:
  app:
    build: 
      dockerfile: "./docker/Dockerfile"
      context: ..
    ports:
      - "9022:9022"
      - "5001:5001"
      - "5002:5002"
    environment:
      BAKER_ACME_PROVIDER_EMAIL: "tim@chargeover.com"
    volumes:
      - data:/data

volumes:
  data: