version: "3.8"

services:
  app:
    container_name: rykelabs-acme-app
    build:
      dockerfile: "./docker/Dockerfile"
      context: ..
      target: $COMPOSE_TARGET
      args:
        BUILD_VERSION: 0.0.0-dev
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "9022:9022"
    expose:
      - "80"
      - "443"
    working_dir: /app/code
    volumes:
      - ../:/app/code

  redis:
    image: redis:6.2.6-alpine3.15
    container_name: rykelabs-acme-redis
    expose:
      - "6379"
    networks:
      - acme-server
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      retries: 3

networks:
  acme-server:
    driver: bridge
