version: "3.8"

services:
  app:
    image: git.rykelabs.com:5050/rykelabs/acme-server:latest
    networks:
      - acme-server
    environment:
      ACME_ENV: "development"
      BAKER_ACME_PROVIDER_EMAIL: "tim@chargeover.com"
      ACME_HOST: "https://acme-staging-v02.api.letsencrypt.org/directory"
      DNSMADEEASY_HTTP_TIMEOUT: "60"
      DNSMADEEASY_PROPAGATION_TIMEOUT: "60"
    volumes:
      - acme-data:/data

volumes:
  acme-data:
