server:
  host: 0.0.0.0
  port: 9022

database:
  host: rykelabs-acme-mariadb
  port: 3306
  user: dev
  pass: password
  name: acme_dev

redis:
  host: 127.0.0.1
  port: 1234
  name: certificate-request

acme:
  email: support@chargeover.com
  host: https://acme-staging-v02.api.letsencrypt.org/directory
  dataPath: /data
  tls:
    port: 443
  http:
    port: 80
  dns:
    provider: dnsmadeeasy

services:
  logger:
    color: true