# secret used for encryption, do not change once set
secret: abcd1234

# controls where the web server listens, note host is used for ACME as well
server:
  host: 0.0.0.0
  port: 9022

# your mariadb database credentials
database:
  host: rykelabs-acme-mariadb
  port: 3306
  user: dev
  pass: password
  name: acme_dev

# your redis credentials
redis:
  host: rykelabs-acme-redis
  port: 6379
  name: certificate-request

# acme server config
acme:
  email: support@chargeover.com
  host: https://acme-staging-v02.api.letsencrypt.org/directory
  dataPath: /data # path to where the certificates are stored
  userAgent: lego-cli/chargeover
  clientTimeout: 60 # client that talks to the remote ACME server e.g. LetsEncrypt. in seconds
  retryLimit: 5 # LetsEncrypt has a rate limit of 5 failures per account, per hostname, per hour
  tls:
    host: 0.0.0.0
    port: 443
  http:
    host: 0.0.0.0
    port: 80
    proxyHeader:
  dns:
    provider: dnsmadeeasy
    # Timeout for DNS propagation check, in seconds. Must be combined with:
    # - DNSMADEEASY_HTTP_TIMEOUT env var, values should be the same as this key
    # - DNSMADEEASY_PROPAGATION_TIMEOUT env var, values should be the same as this key
    timeout: 60

services:
  logger:
    color: true
