# secret used for encryption, do not change once set
secret: abcd1234

# controls where the web server listens, note host is used for ACME as well
server:
  host: 0.0.0.0
  port: 9022

# your mariadb database credentials
database:
  host: rykelabs-acme-mariadb
  port: 3306
  user: dev
  pass: password
  name: acme_dev

# your redis credentials
redis:
  host: rykelabs-acme-redis
  port: 6379
  name: certificate-request

# acme server config
acme:
  email: support@chargeover.com
  host: https://acme-staging-v02.api.letsencrypt.org/directory
  dataPath: /data # path to where the certificates are stored
  tls:
    port: 443
  http:
    port: 80
  dns:
    provider: dnsmadeeasy

services:
  logger:
    color: true
