secret: abcd1234

server:
  host: 0.0.0.0
  port: 9022

redis:
  host: rykelabs-acme-redis
  port: 6379
  name: certificate-request

acme:
  email: support@chargeover.com
  host: https://acme-v02.api.letsencrypt.org/directory
  dataPath: /data
  userAgent: lego-cli/chargeover
  clientTimeout: 60 # in seconds
  retryLimit: 5
  renewal:
    days: 30
    reusePrivateKey: false
    noRandomDelay: false
    alwaysDeactivateAuthorizations: false
    mustStaple: false
  tls:
    host: 0.0.0.0
    port: 443
  http:
    host: 0.0.0.0
    port: 80
    proxyHeader:
  dns:
    provider: dnsmadeeasy
    timeout: 60 # in seconds

services:
  logger:
    color: false
  jwt:
    issuer: RykeLabs
    tokenTTL: 30

plugins:
  haproxy:
    enable: true
    host: rykelabs-ingress-haproxy
    port: 9999
