secret: 12345

server:
  host: 0.0.0.0
  port: 9022

database:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: password
  name: acme

redis:
  host: 127.0.0.1
  port: 6379
  name: certificate-request

acme:
  email: support@chargeover.com
  host: https://acme-v02.api.letsencrypt.org/directory
  dataPath: /data
  userAgent: lego-cli/chargeover
  tls:
    host: 0.0.0.0
    port: 443
  http:
    host: 0.0.0.0
    port: 80
    proxyHeader:
  dns:
    provider: dnsmadeeasy
    timeout: 60 # in seconds

services:
  logger:
    color: false
