server:
  host: 0.0.0.0
  port: 0.0.0.0

database:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: password
  name: test_db

redis:
  host: 127.0.0.1
  port: 1234
  name: certificate-request

acme:
  email: support@chargeover.com
  host: https://acme-v02.api.letsencrypt.org/directory
  dataPath: /data
  tls:
    port: 443
  http:
    port: 80
  dns:
    provider: dnsmadeeasy

services:
  logger:
    color: false