openapi: 3.0.1
info:
  contact:
    email: tim@chargeover.com
    name: API Support
    url: https://git.rykelabs.com/rykelabs/acme-server/-/issues/new
  description: "# Authorization\n\nSome description\n\n<!-- ReDoc-Inject: <security-definitions>\
    \ -->"
  license:
    name: MIT
    url: https://git.rykelabs.com/rykelabs/acme-server/-/blob/main/LICENSE.md
  termsOfService: https://chargeover.com/terms-of-service
  title: ACME API
  version: "1.0"
servers:
- url: https://acme.chargeover.com:9022/api/v1
paths:
  /certificate/request:
    post:
      description: do pong
      requestBody:
        content:
          application/json:
            schema:
              type: integer
        description: Add account
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: ok
      security:
      - ApiKeyAuth: []
      summary: pong example
      tags:
      - idk
      x-codegen-request-body-name: account
  /example/helloworld:
    get:
      description: do ping
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
      summary: ping example
      tags:
      - example
components:
  schemas: {}
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: Authorization
      type: apiKey
x-original-swagger-version: "2.0"
